### PR TITLE
Player class with unit tests

### PR DESCRIPTION
**Pull request by deltaidea**
Unit testing!

Use Biicode to download dependencies. See http://docs.biicode.com/c++. Particularly, we now depend on a unit testing library described below.

Use Catch for unit testing. See https://github.com/philsquared/Catch. It's very easy to use and was easy to set up. It doesn't have any dependencies, which is nice.

To keep things clean and separated, move source to `src/` and tests to `tests/`.

Rewrite `promptUsername()` into a separate class and a method in it: `Player::doNameDialog()`. The name is saved as `Player::name`.

Add new prerequisites and dev cycle to the readme.

See messages for individual commits for more details, or ask questions in #8.

### CODE REVIEW

**Comment by deltaidea** [comment]
Yikes!

I won't merge this until all questions are answered.

**Comment by the-emerald** [comment]
How can I compile this?

**Comment by deltaidea** [comment]
As discussed in PMs: just follow instructions in the readme.

**Comment by deltaidea** [comment]
I used these two articles to write this PR:
- http://www.cplusplus.com/doc/tutorial/classes/ - about classes
- http://www.cplusplus.com/forum/articles/10627/ - about header files

Seems like it all works for both of us, so merge when you're ready.

**Comment by the-emerald** [comment]
Does changing the compilation directions to be `bii build --target user_nameofdirectory_src_main && bin/user_nameofdirectory__src_main‏` solve the problem?

**Comment by the-emerald** [comment]
Yes, it does work. Merging.

**Pull request merged**
