### PR TITLE
Improved the code

### PR DESCRIPTION
**Pull request by seanballais**
Improved the code structure of the source code. I also added a Makefile to simplify the compilation process.

### CODE REVIEW

**Comment by deltaidea** [comment]
Great job!

The only issue I see is moving game version to some inline message.

Generally speaking, meta project info should go into a separate JSON/XML file, or at least to `#define` section. Otherwise you can forget to change it somewhere. It's just encapsulation, and encapsulation is your friend.

**Comment by seanballais** [comment]
You're right on that. I should really place the meta info to a header file so that modifications will be made easier in the future.

**Comment by seanballais** [comment]
The code still needs to be refactored by the way.

**Comment by deltaidea** [comment]
Cool!

Also, ignoring everything and then allowing files manually is messy at best. What files are you trying to ignore?

**Comment by seanballais** [comment]
I was ignoring the compiled executable file.

**Comment by deltaidea** [comment]
Yeah, that's much better!

Now, about "Removed unnecessary comments". I'd say, all the comments are currently confusing.

I mean,

``` C++
int rng = rand() % 20 + 30; //redo rng
```

and:

``` C++
int month = 0; // Month
```

Don't you say‽

I think it's OK to just remove them all. except the `// By suclearnub` notice at the top, that's to be discussed separately.

Also, turns out, I'm a Collaborator, so I can merge this afterwards!

**Comment by the-emerald** [comment]
Remove it - I'm ok with it.

**Comment by seanballais** [comment]
Done. @suclearnub, do you mind if I ask you why you added the unnecessary comments in the first place?

**Comment by deltaidea** [comment]
My guess is - because is seemed like a good idea. You should document code, right?

Edit: to be fair, some of the comments were mine, because this is the first time I work with C++ as well, so I added links to SO answers about confusing syntax details.

ProTip: do _not_ write comments about _how_ your code works. Only write _why_ it works that way.

If you need to write comments about how it works, then you literally think that nobody will understand it. Refactor it instead or don't comment at all.

Bad comment:

``` JavaScript
// Iterating over posts.
for (i = 0; i <= posts.length; i++) {
...
}
```

Good comment:

``` JavaScript
// Voting algorithm doesn't update positions of posts on the front page. Updating manually:
for (i = 0; i <= posts.length; i++) {
...
}
```

This doesn't apply to any external documentation, only to inline comments.

**Comment by the-emerald** [comment]
Yup, it definitely seemed like a good idea. Maybe it's not.

**Comment by seanballais** [comment]
:+1: @deltaidea Agreed. I cringe a little whenever I see code commented in a bad way.

And, any more comments on my PR? :)

**Comment by deltaidea** [comment]
Pulled it and compiled. Everything works as expected. :+1:

**Comment by seanballais** [comment]
So, @suclearnub. Any plans on refactoring the code?

**Comment by the-emerald** [comment]
Definitely. Now that I read it, it's a bit messy...

**Comment by seanballais** [comment]
Don't hesitate to notify me if you need help refactoring. I'll help when I have time.

**Comment by the-emerald** [comment]
Any ideas on how to improve it? I have no idea where to start.

**Comment by deltaidea** [comment]
See #7.

**Comment by seanballais** [comment]
@suclearnub Start using headers.

**Pull request merged**
